apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactdemo-deployment
  labels:
    app: reactdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactdemo
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 0
  template:
    metadata:
      labels:
        app: reactdemo
    spec:
      containers:
      - name: reactdemo
        image: reactdemo
        env:
        - name: PORT
          value: "3000"
        - name: CI
          value: "true"
        - name: NODE_ENV
          value: "development"
        ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: reactdemo-service
spec:
  selector:
    app: reactdemo
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer