apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
  - image: reactdemo
    context: .
    sync:
      manual:
        - src: './react-demo/public/**/*'
          dest: /app/public/
        - src: './react-demo/src/**/*'
          dest: /app/src/
deploy:
  kubectl:
    manifests:
      - k8s-*